### ISSUE TITLE
scripts and pre-trained models for cityscapes?

### ISSUE THREAD

**Issue by TiankaiHang** [Jia-Research-Lab/Context-Aware-Consistency#1]
Thanks for your nice work!

Will scripts and pre-trained models for cityscapes be published?

**Comment by X-Lai** [comment]
Thanks for your comment. I have already uploaded the cityscapes dataloader and also the sample cityscapes config files. The pre-trained models are also available in https://mycuhk-my.sharepoint.com/:f:/g/personal/1155154502_link_cuhk_edu_hk/EpHdT2JFT11FpsUc4jHE3CoB2wUZ5tQo_W0QzzqHdNtF-A?e=yx2Xha
