### ISSUE TITLE
How to visualize the result using T-Sne？ 

### ISSUE THREAD

**Issue by Chic-J** [Jia-Research-Lab/Context-Aware-Consistency#12]
Thanks for your great work！
but i wonder how to visualize the result？Are there any codes？I try to solve it for several days，but can not  figure it out...

**Comment by 2679622694** [comment]
> 感谢您的出色工作！
> 但我想知道如何将结果可视化？有代码吗？我尝试解决了几天，但无法弄清楚......
I have the same question. Have you solved this problem？
