### ISSUE TITLE
Question of the table

### ISSUE THREAD

**Issue by ghost** [Jia-Research-Lab/Context-Aware-Consistency#19]
Hi,

Thanks for your work!

I'm wondering your result on this table is based on deeplabv3+ or not.
![result](https://user-images.githubusercontent.com/33716428/133530083-7c6f953f-c1cc-4865-9d7c-972c36a9acf1.png)

Cheers,

**Comment by X-Lai** [comment]
Thanks for your interest in our work. The experiments you mentioned are based on PSPNet, which follows CCT.
