### ISSUE TITLE
The exact number of training data with 1/16, 1/8, 1/4 and full labeled data

### ISSUE THREAD

**Issue by wqhIris** [Jia-Research-Lab/Context-Aware-Consistency#2]
Thank you for your nice work!
Would it be possible to provide the exact number of labeled data and unlabeled data with 1/16, 1/8, 1/4 setting of two datasets?

**Comment by X-Lai** [comment]
Thanks a lot for your question. As you can see from https://github.com/Jia-Research-Lab/Context-Aware-Consistency/tree/master/dataloaders/city_splits0, the number of labeled training samples for the 1/8 and 1/4 settings are 372 and 744 respectively. And for Pascal VOC, the number of labeled training samples for the 1/16, 1/8 and 1/4 settings are 662, 1323 and 2645 respectively, which can be seen from https://github.com/Jia-Research-Lab/Context-Aware-Consistency/tree/master/dataloaders/voc_splits1.

**Comment by X-Lai** [comment]
I will close this issue. If you have further questions, feel free to reopen it. Thanks a lot.
