### ISSUE TITLE
Can you explain why 'unsupervised_w' is set  '30' which is very large in config file, thanks you!

### ISSUE THREAD

**Issue by wuyunxiangwyx** [Jia-Research-Lab/Context-Aware-Consistency#28]
in addition，iteration per epoch is constant in train.py code , 'iter_per_epoch = 1157', can i set it with 'len(unsupervised_loader)', thank you!

**Comment by X-Lai** [comment]
Thanks for your interest in our work. The hyper-parameter ```unsupervised_w``` is actually not used in our codes. If you want to know the unsupervised loss weight, you can refer to the hyper-parameter ```weight_unsup```. Besides, fixing ```iter_per_epoch```  to 1157 is just for fair comparisons between models with different datalists. You can change it if you want to.
