### ISSUE TITLE
CPU RAM explodes after ~60 iterations.

### ISSUE THREAD

**Issue by nikhilbyte** [Jia-Research-Lab/Context-Aware-Consistency#4]
Hello, I was training your model using:

python3 train.py --config configs/voc_cac_deeplabv3+_resnet50_1over8_datalist0.json

The training starts but till 60 iterations of the 1st epoch the RAM explodes and the system crashes.

GPU: P100 16GB
CPU RAM: 25gb
Batch SIze: 2

**Comment by X-Lai** [comment]
I guess this happens because the RAM may be a little small. In our experiments, the CPU RAM limit is 100GB.

**Comment by nikhilbyte** [comment]
So can you think of a workaround for it ?

**Comment by X-Lai** [comment]
You may increase your RAM.

**Comment by X-Lai** [comment]
I will close this issue. If you have further problems, welcome to reopen it.
