### ISSUE TITLE
Confusion regarding unsupervised labels.

### ISSUE THREAD

**Issue by nikhilbyte** [Jia-Research-Lab/Context-Aware-Consistency#5]
I see that the algorithm uses labels for unsupervised data as well.
How to train without using the labels for unsupervised data ?

**Comment by X-Lai** [comment]
Thank you for your comment.
We note that we DON'T use the labels for unsupervised data for training the model. We pass the variable 'target_ul' into the model, but it is NOT used for training, instead just to calculate some statistics (these codes to calculate the statistics are cleaned, so we actually don't use the variable 'target_ul' inside the model).

**Comment by nikhilbyte** [comment]
Thank you so much for your response. 
So according to what you mentioned just now, if I want to train the model using a custom dataset, I can pass blank (255,255) for the variable target_ul and the performance won't get affected because of this. 
Also would you recommend passing those or is there a way of eliminating the variable target_ul altogether ?
Thank you

**Comment by X-Lai** [comment]
You can eliminate the variable 'target_ul' [here](https://github.com/Jia-Research-Lab/Context-Aware-Consistency/blob/master/models/model.py#L74). And then you don't need to pass this variable to the model.

**Comment by nikhilbyte** [comment]
Thanks a lot.
