### ISSUE TITLE
Baselines compared ...

### ISSUE THREAD

**Issue by TiankaiHang** [Jia-Research-Lab/Context-Aware-Consistency#6]
Hi, thanks for your nice work!

You have  listed some results of other methods (such as CCT), have you just re-implement the method under your settings?

As we know, the splits of dataset differ in those semi-sup papers.

Thanks.

**Comment by X-Lai** [comment]
Yes, you are right. The splits of datasets differ in different works and they also don't release the data lists, which makes it hard to compare with other works. Therefore, to fairly compare with different state-of-the-art methods, we use their official codes with our data lists.
The data lists we use are released in [here](https://github.com/Jia-Research-Lab/Context-Aware-Consistency/tree/master/dataloaders). Thanks for your comment.

**Comment by TiankaiHang** [comment]
OK, thanks!
