### ISSUE TITLE
Where to get the 1/2 and 1/16 split for the datasets?

### ISSUE THREAD

**Issue by TiankaiHang** [Jia-Research-Lab/Context-Aware-Consistency#7]
As the subject.

Thanks!!

**Comment by X-Lai** [comment]
For both PASCAL VOC and Cityscapes, we don't use 1/2 split in our experiments.
However, we did conduct experiments on 1/16 split for PASCAL VOC. In this split, there are 662 labeled samples, where you can get from [split0](https://github.com/dvlab-research/Context-Aware-Consistency/blob/master/dataloaders/voc_splits0/662_train_supervised.txt), [split1](https://github.com/dvlab-research/Context-Aware-Consistency/blob/master/dataloaders/voc_splits1/662_train_supervised.txt), [split2](https://github.com/dvlab-research/Context-Aware-Consistency/blob/master/dataloaders/voc_splits2/662_train_supervised.txt).
