### ISSUE TITLE
如何选择重叠区域

### ISSUE THREAD

**Issue by xyf159** [Jia-Research-Lab/Context-Aware-Consistency#9]
你好，请问如何确定论文中随机选取的重叠区域刚好是目标所在的区域（伪标签的值）？如果选取的重叠区域不是目标所在，那对比损失还有意义吗？

**Comment by X-Lai** [comment]
I am a little confused about your question. I think you may misunderstand something. 

The overlapping region is randomly selected. In particular, we simply select two random crops from a single image. If the IoU (intersection over union) between the two crops is not within [0.1, 1.0], we will resample two random crops until they satisfy the requirement. The overlapping region is thus randomly formed. 

Actually, we don't care what content is in the overlapping region. Our goal is simply maintain a context-aware consistency over the overlapping region in a pixel-to-pixel manner with the proposed contrastive loss.

**Comment by xyf159** [comment]
Thanks for your reply。
